"use strict";
/* ---------- DEPARTMENTS: budget, status, evidence ---------- */
/* status: strong | mixed | weak | stressed | unverified | improving */
const DEPTS = [
 {n:"Finance (taxes, GST, ED, accounts)",b:"Interest = 40% of revenue receipts",s:"mixed",e:`The CAG found 33,973 utilisation certificates worth Rs 54,282 crore outstanding across 15 ministries at March 2025 (paperwork missing, not proven theft). Interest takes about 40% of revenue receipts.`,k:["cag_w","cag_w2","exprs"]},
 {n:"Enforcement Directorate (under Finance)",b:"4,622 PMLA cases in 5 years",s:"mixed",e:`Cases hit a four-year high (1,080) in 2025-26, but convictions in the five years were 43. The government cites a 94.82% rate among decided cases. For 193 politicians booked in ten years, there were 2 convictions.`,k:["ed_wire","ed_a2z","ed_dh","ed_wire2"]},
 {n:"Defence",b:"Rs 7.85 lakh crore (about 2% of GDP)",s:"mixed",e:`Capital outlay rose about 22% to Rs 2.19 lakh crore. Revenue (pay, pensions) still takes about 72% of the budget, against 60% recommended by a parliamentary committee. Defence's share of Union spending fell from 17.1% (FY15) to 14.7%.`,k:["def_idsa","def_prs","def_iadb"]},
 {n:"Home Affairs (security, police funding, NCRB)",b:"Crime rate 448.3 per lakh (2023)",s:"weak",e:`Peace index rank fell to 127th. Manipur has displaced 60,000+ people and no convictions after three years. The Naxal-free claim has no independent audit. Over half of accused in crimes against Northeasterners in Delhi over 12 years were untraced.`,k:["gpi26","manipur","manipur2","naxal","ncrb_n"]},
 {n:"External Affairs",b:"See the Foreign reel",s:"mixed",e:`Trade deal with the EU concluded in January; US tariff cut announced then disrupted by a court ruling; China ties thawing but the trade deficit hit a record $112 billion; Pakistan mediated the 2026 Iran ceasefire and India said little publicly.`,k:["fp_eu","trade2","fp_cn","fp_iran"]},
 {n:"Railways",b:"Safety allocation Rs 1.20 lakh crore",s:"improving",e:`The Minister told Parliament that serious accidents fell from 135 (2014-15) to 16 (2025-26). Kavach train protection is commissioned on 2,569 route km, with 15,512 km planned. These are government figures; I found no independent audit.`,k:["rail","rail_dd"]},
 {n:"Civil Aviation",b:"AI171 final report pending",s:"stressed",e:`Air India flight AI171 (June 2025) killed 241 of 242 on board plus 19 on the ground. The cause is still not established. IndiGo cancelled over 5,000 flights in December 2025 and the regulator ordered a 10% schedule cut.`,k:["air_w","air_e"]},
 {n:"Health and Family Welfare",b:"1.43% of GDP (2022-23)",s:"weak",e:`Public health spending is well under the 2.5% goal; 43.4% of health costs are paid out of pocket. Child stunting 33.8%.`,k:["nha","nfhs"]},
 {n:"Education (school and higher)",b:"About 4% of GDP by one count",s:"weak",e:`NEET-UG 2026 (22.7 lakh candidates) was cancelled on 12 May after a leak; NTA insiders were among those arrested. Higher Education has Rs 14,360 crore in outstanding utilisation certificates. A 2024 leak also hit NEET.`,k:["neet26","cag_w","edu"]},
 {n:"Rural Development",b:"VB-G RAM G Rs 95,692 crore",s:"mixed",e:`MGNREGA was replaced by the VB-G RAM G Act in December 2025. MGNREGS itself is allocated Rs 30,000 crore, down from Rs 86,000 crore. Activists said several aspects of the new law were unclear.`,k:["exprs","vbg"]},
 {n:"Jal Shakti (Jal Jeevan Mission)",b:"Rs 67,670 crore in 2026-27",s:"mixed",e:`The Minister says 15.83 crore rural homes have a tap (from 3.23 crore in 2019); the 2024 deadline moved to 2028. A verification found 26% of villages checked non-functional. CAG found fake or reused invoices in Rajasthan.`,k:["jjm_air","jjm_aud","jjm_cag"]},
 {n:"Housing and Urban Affairs",b:"Rs 18,273 crore certificates pending",s:"unverified",e:`The highest amount of outstanding utilisation certificates of any ministry in the CAG report. That means the end-use of the grants could not be confirmed on paper.`,k:["cag_w"]},
 {n:"Agriculture and Fertilisers",b:"PM-KISAN Rs 63,500 crore, flat 3rd year",s:"stressed",e:`Fertiliser subsidy is Rs 1.71 lakh crore. The monsoon is 15% short. A government agency claim that a scheme doubled the income of 75,000 farmers did not hold up when a newsroom visited listed farmers.`,k:["pmk","exprs","monsoon","nl_farm"]},
 {n:"Corporate Affairs (PM Internship)",b:"1 crore internships in 5 years",s:"weak",e:`By April 2026, companies posted 2.97 lakh internships, 1.73 lakh offers, about 18,000 joined and about 5,200 finished. Under 0.2% of the five-year outlay was spent.`,k:["nl_int"]},
 {n:"Labour and Employment",b:"29 laws into 4 codes",s:"mixed",e:`The four Labour Codes came into force on 21 November 2025 and final central rules on 8 May 2026. Most states were still implementing them in mid-2026.`,k:["lab_k","lab_f"]},
 {n:"Commerce (trade deals)",b:"EU deal; US interim deal",s:"mixed",e:`EU-India FTA concluded 27 January 2026 (ratification not verified). The US deal cut tariffs from 50% to 18%, then the US Supreme Court struck down the emergency tariffs and the deal stayed unsettled.`,k:["fp_eu","trade","trade2"]},
 {n:"Petroleum, Power and Energy",b:"88% of LPG imports via Hormuz",s:"stressed",e:`The Hormuz closure caused LPG shortages and protests. Non-fossil capacity reached 50%, but coal still produces most electricity.`,k:["hormuz","lpg","renew"]},
 {n:"Payments (Finance, NPCI, RBI)",b:"UPI 24.5 billion payments a month",s:"mixed",e:`UPI works at scale. From 15 October 2026 a 0.4% merchant fee applies to payments above Rs 2,000, ending zero-MDR. The Finance Ministry had called such reports baseless in June 2025.`,k:["upi","upi_bs","upi_25"]},
 {n:"Statistics (MoSPI, Census)",b:"IMF grade C",s:"weak",e:`GDP was rebased in February 2026 and the IMF grades national accounts C. The census, delayed since 2021, started houselisting in April 2026.`,k:["imfc","gdpnew","census"]},
 {n:"Election Commission",b:"91 lakh names removed in Bengal",s:"mixed",e:`The voter-roll revision was upheld by the Supreme Court on 27 May, with room for individual challenges. Opposition leaders allege 'vote chori'; the Commission rejects the claims as baseless and asked for sworn proof.`,k:["sir","sir2","vc_adr","vc_tr"]},
 {n:"Parliament",b:"Lok Sabha 15% productive (Monsoon 2026)",s:"weak",e:`11 of 12 bills passed with none sent to committees; seven got five minutes or less of Lok Sabha discussion. Question Hour ran 1% of scheduled time.`,k:["par_bs","par_out","par_prs"]}
];

/* ---------- CASE FILES (all levels, all parties) ---------- */
const CASES = [
 {c:"Electoral bonds",who:"Central law; all parties",f:`Supreme Court struck the scheme down on 15 Feb 2024. Bonds worth Rs 16,518 crore were bought (2018-Jan 2024). BJP took about 48% of bond donations to the 20 main parties (Rs 6,566 crore), Congress Rs 1,122 crore, TMC Rs 1,092 crore. TMC got 95% and BJD 93% of their donations via bonds.`,st:"Closed by court; donor links studied",k:["eb_adr","eb_adr2","eb_trib","eb_bs"]},
 {c:"Donors under investigation",who:"BJP and others",f:`Al Jazeera found all top-10 corporate donors probed by central agencies in five years gave to the BJP (over Rs 1,300 crore). A research paper counted about 30 firms (Rs 335 crore) donating while under agency action. The BJP says this is no evidence of wrongdoing. No court has found quid pro quo.`,st:"Alleged; not proven",k:["eb_aj","eb_nat"]},
 {c:"Adani Group",who:"Private group; US and Indian regulators",f:`US indictment (Nov 2024) alleged about $265 million in bribes for solar contracts. In May 2026 Gautam and Sagar Adani settled the SEC civil case for $6 million and $12 million without admitting or denying; the criminal case was reported dismissed. SEBI cleared the group of the 2023 Hindenburg manipulation claims (Sept 2025). India's Law Ministry twice declined to serve US summons. The group denies wrongdoing.`,st:"US cases settled or dismissed; questions remain",k:["adn_sec","adn_bs","adn_jan","adn_sebi"]},
 {c:"West Bengal SSC recruitment",who:"TMC government (until May 2026)",f:`The Supreme Court on 3 April 2025 upheld voiding all 25,753 appointments from the 2016 test (23 lakh candidates, 24,640 posts; OMR tampering, rank-jumping), calling the process tainted beyond resolution. Untainted teachers also lost jobs; new recruitment ordered.`,st:"Court-verified; fallout continues",k:["wbssc","wbssc2"]},
 {c:"NEET-UG paper leak (2024 and 2026)",who:"Union agency NTA",f:`The 3 May 2026 exam (22.7 lakh candidates) was cancelled on 12 May after up to 120 to 140 questions matched a circulated guess paper. The CBI probe led to arrests including NTA insiders. It follows a 2024 NEET controversy. Parliament passed an amended Public Examinations law in the Monsoon Session.`,st:"CBI probe; re-exam",k:["neet26","par_bs"]},
 {c:"Unaccounted grants (utilisation certificates)",who:"15 Union ministries",f:`33,973 certificates worth Rs 54,282 crore outstanding at 31 March 2025; Rs 38,288 crore from the last three years; oldest from 1985-86. The CAG does not say the money was stolen. Delhi's BJP government raised a similar issue against the earlier AAP government (Rs 3,760 crore).`,st:"Audit finding; no official reply found",k:["cag_w","cag_w2","cag_ne"]},
 {c:"Jal Jeevan Mission contracts",who:"Centre and states (Rajasthan audited)",f:`CAG in Rajasthan found Rs 7.07 crore paid on fabricated, cancelled or reused invoices and Rs 122 crore paid without third-party inspection. Nationally, 607 cases were flagged in 20 states; 236 contractors blacklisted.`,st:"Departmental action; audits",k:["jjm_cag","jjm_aud"]},
 {c:"PM Internship scheme",who:"Union Corporate Affairs",f:`A flagship 2024 promise: 30 lakh internships in two years. RTI shows about 5,200 people finished. Advertising cost nearly as much as the stipends.`,st:"Not a scam; a delivery gap",k:["nl_int"]},
 {c:"Election-roll disputes",who:"Election Commission; Congress",f:`Allegations of 'vote chori' (Mahadevapura, Aland) were rejected by the Commission as baseless; it admitted failed deletion attempts in Aland in 2023 and filed an FIR. I found no independent finding of systematic fraud, and no full clearance either.`,st:"Disputed",k:["vc_adr","vc_tr"]}
];

/* ---------- PAPER vs GROUND ---------- */
const GROUND = [
 {t:"Tap water in every rural home",p:`15.83 crore of about 19.36 crore rural homes have a tap connection (Minister, March 2026).`,g:`A verification found 26% of villages checked with non-functional supply and 6% irregular. Rajasthan's CAG audit found only 49.6% of the household target met. Deadline moved from 2024 to 2028.`,k:["jjm_air","jjm_aud","jjm_cag"],tone:"orange"},
 {t:"1 crore internships in five years",p:`30 lakh in the first two years (Budget 2024).`,g:`2.97 lakh posted, 1.73 lakh offers, about 18,000 joined, about 5,200 finished (RTI, April 2026).`,k:["nl_int"],tone:"red"},
 {t:"Income of 75,000 farmers doubled",p:`A government agency (ICAR) said a scheme doubled income for 75,000 farmers.`,g:`Reporters found listed farmers who did not know, had sold their land, or had left farming.`,k:["nl_farm"],tone:"red"},
 {t:"Record foreign investment",p:`Gross FDI hit a record $94.84 billion in FY26.`,g:`Net FDI (after repatriation and Indian firms investing abroad) was $6.95 billion, against $27.99 billion in FY23.`,k:["fdi_ob","fdi_fed"],tone:"orange"},
 {t:"Fast growth",p:`7.8% real GDP growth in Apr-Jun 2026.`,g:`The deflator (2.5%) is below consumer and wholesale inflation. The IMF grades the accounts C. Old and new series are not shown side by side.`,k:["gdpq1","gdpdebate","imfc"],tone:"orange"},
 {t:"Unemployment is low",p:`3.1% (2025, usual status).`,g:`5.4% on weekly status; youth 15.9%; a quarter of young people are not working, studying or training.`,k:["plfsa","plfsq"],tone:"orange"},
 {t:"UPI will stay free",p:`Finance Ministry, June 2025: reports of MDR were "completely false, baseless".`,g:`From 15 October 2026 a 0.4% fee applies to merchant payments above Rs 2,000. The stated reason is running costs of about Rs 20,000 crore a year.`,k:["upi_25","upi_bs","upi_tt"],tone:"red"},
 {t:"Railways have become safer",p:`Serious accidents fell from 135 to 16 in a decade (Minister).`,g:`I found no independent audit. Kavach covers 2,569 route km, with 15,512 planned.`,k:["rail","rail_dd"],tone:"grey"},
 {t:"Maoist insurgency ended",p:`Home Minister, 30 March 2026: virtually Naxal-free.`,g:`No independent verification found.`,k:["naxal"],tone:"grey"},
 {t:"Extreme poverty nearly gone",p:`5.3% at $3 a day (2022-23).`,g:`Survey methods changed. Income inequality is far higher (Gini 62). Child stunting is 33.8%.`,k:["pov","pov2","gini","nfhs"],tone:"orange"}
];

/* ---------- FOREIGN RELATIONS ---------- */
/* dir: improving | mixed | weak (strained) | unverified */
const RELATIONS = [
 {c:"United States",dir:"mixed",f:`Tariffs on most Indian goods cut from 50% to 18% in a February 2026 interim deal, then the US Supreme Court struck down the emergency tariffs and the deal stayed unsettled. The $100,000 H-1B fee rule was extended to September 2027 but is blocked in court. Washington's outreach to Islamabad in 2025 soured ties.`,k:["trade","trade2","h1b","fp_ch"]},
 {c:"China",dir:"improving",f:`Trade hit a record $151.1 billion in the year to March 2026, and India's deficit a record $112.16 billion. Direct flights resumed and investment curbs (Press Note 3) eased in March 2026; Modi and Xi met at the BRICS summit in New Delhi. Analysts call it a tactical accommodation, not a reset. Border differences remain.`,k:["fp_cn","fp_eaf"]},
 {c:"Russia",dir:"mixed",f:`The 2025 US penalty tariff was tied to India's Russian oil purchases. India's Russian crude imports fell in January 2026 during US trade talks as it diversified suppliers.`,k:["fp_ch","trade"]},
 {c:"Pakistan",dir:"weak",f:`After Pahalgam (April 2025) India suspended the Indus Waters Treaty, cut visas and trade; the May 2025 conflict lasted four days. In 2026 Pakistan helped mediate the US-Israel-Iran ceasefire, which Indian commentators saw as a setback for India's standing.`,k:["fp_pk","sindoor","fp_iran"]},
 {c:"European Union",dir:"improving",f:`Free trade agreement concluded 27 January 2026, cutting or removing tariffs on 96.6% of EU goods and 99.5% of Indian goods (op-ed source; ratification not verified).`,k:["fp_eu"]},
 {c:"Gulf and Iran",dir:"weak",f:`India tried to stay neutral in the 2026 Iran war under pressure from Washington and Beijing. The Hormuz closure hit LPG supplies. Around half of the 18.5 million Indians working abroad live in the Gulf.`,k:["fp_iran","hormuz","remit"]},
 {c:"Bangladesh, Nepal and neighbours",dir:"weak",f:`Relations with Bangladesh have been down since Sheikh Hasina was removed and fled to India in 2024. Nepal saw Gen Z protests in 2025. Chatham House called 2025 arguably India's hardest foreign-policy year.`,k:["fp_ch"]},
 {c:"UK, Japan, Australia, ASEAN",dir:"unverified",f:`Not verified in this session.`,k:[]}
];

/* ---------- POLICY TIMELINE ---------- */
const POLICIES = [
 {d:"1 Jan 2020",t:"Zero-MDR on UPI",e:`Merchant fees removed by gazette notification; banks and fintechs compensated by a yearly subsidy (Rs 2,196 crore paid in 2025-26).`,k:["upi_bs","upi_op"]},
 {d:"12 Jun 2025",t:"Finance Ministry denies MDR plan",e:`Called reports of MDR on UPI "completely false, baseless, and misleading".`,k:["upi_25"]},
 {d:"11-12 Aug 2025",t:"Income-tax Act 2025 passed",e:`Passed Lok Sabha without debate on 11 August and Rajya Sabha on 12 August. In force 1 April 2026.`,k:["itact"]},
 {d:"22 Sep 2025",t:"GST rate cuts",e:`Rates cut on many goods. October collections still grew 4.6%. Refunds later rose sharply.`,k:["gstoct","gst"]},
 {d:"21 Nov 2025",t:"Four Labour Codes in force",e:`29 laws merged into 4. Final central rules notified 8 May 2026; states still implementing.`,k:["lab_k","lab_f"]},
 {d:"Dec 2025",t:"MGNREGA replaced by VB-G RAM G",e:`In 2026-27 VB-G RAM G gets Rs 95,692 crore, MGNREGS Rs 30,000 crore (from Rs 86,000 crore).`,k:["vbg","exprs"]},
 {d:"1 Feb 2026",t:"Union Budget 2026-27",e:`Deficit target 4.3%. Slabs unchanged. PM-KISAN flat at Rs 63,500 crore for the third year. Defence Rs 7.85 lakh crore.`,k:["budgetprs","pmk","def_prs"]},
 {d:"Mar 2026",t:"Chinese investment curbs eased",e:`Press Note 3 (2020) was amended to relax approval rules on investment from land-border countries.`,k:["fp_eaf"]},
 {d:"Mar 2026",t:"Parliamentary committee: zero-MDR unsustainable",e:`The Finance committee said the zero-MDR regime could not last. The US trade representative also listed it as a trade barrier.`,k:["upi_tt"]},
 {d:"Aug 2026",t:"Monsoon Session: 11 bills, no committee referrals",e:`Lok Sabha worked 15% of its time. Seven bills got five minutes or less of discussion; a bill raising Supreme Court judges got four.`,k:["par_bs","par_prs"]},
 {d:"15 Sep 2026",t:"0.4% MDR on UPI payments above Rs 2,000",e:`Effective 15 October 2026. Capped at Rs 300 for payments of Rs 75,000 or more. GST of 18% applies on the fee. P2P transfers and payments up to Rs 2,000 stay free (about 96% of merchant payments).`,k:["upi_bs","upi_op","upi_dt"]}
];

/* ---------- BENEFITS ---------- */
const CASHT = [
 {s:"Maharashtra",sch:"Majhi Ladki Bahin",amt:"Rs 1,500 / month",b:26000,note:"Beneficiaries 24 million to 16.6 million after checks; 2026 outlay cut 42%.",pc:"bjp",k:["cash_bs","cash_dp"]},
 {s:"West Bengal",sch:"Annapurna Bhandar (was Lakshmir Bhandar)",amt:"Rs 3,000 / month (was 1,500)",b:36000,note:"Budgeted for 2026-27; about 11% of revenue receipts.",pc:"bjp",k:["cash_bs","cash_dp"]},
 {s:"Madhya Pradesh",sch:"Ladli Behna",amt:"Monthly",b:23883,note:"Budget 2026-27.",pc:"bjp",k:["cash_dp"]},
 {s:"Bihar",sch:"Mukhyamantri Mahila Rozgar Yojana",amt:"Rs 10,000 one-time (up to Rs 2 lakh)",b:12500,note:"About 1.25 crore women, paid around the 2025 election; opposition called it an 'official bribe'.",pc:"bjp",k:["bihar_dh","bihar_prs"]},
 {s:"Karnataka",sch:"Gruha Lakshmi (guarantees)",amt:"Monthly",b:null,note:"CAG noted guarantees raised the revenue deficit; infrastructure spending was Rs 5,229 crore lower in 2023-24.",pc:"inc",k:["cash_dp"]}
];
