"use strict";
/* ---------- SOURCES ---------- */
const SRC = {
  gdpq1:["MoSPI press note: GDP estimates, Q1 2026-27","https://www.mospi.gov.in/uploads/latestReleases/latest_release_1788172583113_d65a77cf-240e-4491-82ee-59f78618fa41_Press_Note_on_GDP_Estimates_for_Q1_2026-27.pdf","Official"],
  gdpnew:["MoSPI press note: new GDP series, base year 2022-23","https://www.mospi.gov.in/uploads/latestReleases/latest_release_1772189865181_f040336d-bc57-4aed-b80f-586d9ccb279e_Press_Note_on_New_Series_of_GDP_Estimates_with_Base_Year_2022-23_27022026.pdf","Official"],
  gdpdebate:["Onmanorama: explainer on the GDP rebase and deflator debate","https://www.onmanorama.com/news/business/2026/09/05/did-modi-government-deliberately-doctor-gdp-figures-to-project-illusory-growth.html","Press"],
  imf6:["DSIJ: IMF April 2026 table puts India 6th","https://insights.dsij.in/dsijarticledetail/india-slips-to-6th-what-the-imfs-latest-gdp-rankings-actually-tell-us-id010-56633","Press"],
  budgetprs:["PRS: Union Budget 2026-27 analysis","https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf","Analysis"],
  exprs:["PRS: Analysis of expenditure 2026-27","https://prsindia.org/files/budget/budget_parliament/2026/Analysis_of_Expenditure_2026-27.pdf","Analysis"],
  gst:["Business Standard: GST collections, August 2026","https://www.business-standard.com/economy/news/gst-collections-august-2026-gross-revenue-imports-refunds-126090100504_1.html","Press"],
  gstoct:["AIR: GST collections rise 4.6% in October 2025 despite rate cuts","https://www.newsonair.gov.in/gst-collections-rise-4-6-to-over-%E2%82%B91-95-lakh-crore-in-october-despite-rate-cuts/","Official"],
  itr:["Business Standard: 6.68% of population filed returns in FY24 (reply in Parliament)","https://www.business-standard.com/finance/news/only-6-68-of-population-filed-income-tax-return-in-fy24-govt-tells-house-124121700768_1.html","Press"],
  slabs:["Outlook Money: new-regime income tax slabs","https://www.outlookmoney.com/tax/income-tax-slabs-for-fy-2025-26-key-faqs-taxpayers-should-know-for-effective-tax-planning","Press"],
  ita25:["ClearTax: Income-tax Act 2025 FAQ (in force from 1 April 2026)","https://cleartax.in/s/income-tax-act-2025-frequently-asked-questions","Analysis"],
  oecd:["OECD: Revenue Statistics 2025","https://www.oecd.org/en/publications/2025/12/revenue-statistics-2025_07ca0a8e.html","Official"],
  taxf:["Tax Foundation: top personal income tax rates in Europe","https://taxfoundation.org/data/all/eu/top-personal-income-tax-rates-europe/","Analysis"],
  rbi:["Forbes India: RBI policy, August 2026","https://www.forbesindia.com/article/news/rbi-mpc-live-updates-august-2026-repo-rate-sanjay-malhotra-policy-announcement-liveblog/2996705/1","Press"],
  cpi:["Trading Economics: India CPI inflation","https://tradingeconomics.com/india/inflation-cpi","Secondary"],
  fx:["Trading Economics: Indian rupee","https://tradingeconomics.com/india/currency","Secondary"],
  fx2:["Daily Pioneer: rupee closes at 95.89","https://dailypioneer.com/news/slug-lite/rupee-closes-unchanged-at-95-89-against-us-dollar?year=2026","Press"],
  fcnr:["Finnovate: why the rupee is weak despite dollar inflows","https://www.finnovate.in/learn/blog/why-rupee-weak-despite-dollar-inflows-2026","Analysis"],
  resv:["Wikipedia: Foreign-exchange reserves of India (RBI weekly data)","https://en.wikipedia.org/wiki/Foreign-exchange_reserves_of_India","Secondary"],
  monsoon:["Business Today: weakest monsoon in years","https://www.businesstoday.in/india/story/india-monsoon-rainfall-deficit-17-year-low-crop-food-inflation-fears-556311-2026-09-18","Press"],
  foodinf:["News24: El Nino, monsoon deficit and food inflation","https://news24online.com/india/el-nino-2026-india-heads-for-driest-monsoon-since-2009-as-15-rainfall-deficit-raises-crop-food-inflation-fears/927931","Press"],
  plfsq:["Policy Edge: PLFS quarterly bulletin, April-June 2026","https://www.policyedge.in/p/q1-2026-plfs-shows-youth-unemployment-rising-as-labour-participation-softens","Analysis"],
  plfsa:["PIB: PLFS annual report 2025","https://www.pib.gov.in/PressReleasePage.aspx?PRID=2246009&reg=3&lang=1","Official"],
  plfsm:["Civilsdaily: PLFS monthly bulletin, June 2026","https://www.civilsdaily.com/news/periodic-labour-force-survey-plfs-monthly-bulletin-june-2026/","Secondary"],
  mfg:["India Sea Trade News: manufacturing share of GDP (DPIIT)","https://indiaseatradenews.com/?p=97454","Press"],
  nha:["PIB: National Health Accounts 2022-23","https://www.pib.gov.in/PressReleasePage.aspx?PRID=2265816&lang=1&reg=3","Official"],
  nhp:["Tribune: health spending and the 2.5% pledge","https://www.tribuneindia.com/news/nation/declining-trends-in-out-of-pocket-health-spending-419160","Press"],
  edu:["Tribune: education spending near 4% vs 6% target (Azim Premji University)","https://www.tribuneindia.com/news/india/indias-education-spending-remains-at-4-of-gdp-below-neps-6-target/","Press"],
  edu2:["Careers360: Economic Survey, education at 2.7% of GDP","https://news.careers360.com/economic-survey-india-highlights-percentage-gdp-education-budget-central-state-government/amp","Press"],
  hdr:["UN India: Human Development Report 2025, India data","https://india.un.org/en/node/294474","Official"],
  hdrtop:["UNDP India: India ranks 130 of 193","https://www.undp.org/india/press-releases/indias-human-development-continues-make-progress-ranks-130-out-193-countries","Official"],
  rd:["Electronics For You: DST R&D statistics 2025-26","https://www.electronicsforyou.biz/industry-buzz/indias-rd-spending-rises-but-research-intensity-remains-below-1-of-gdp/","Press"],
  rd2:["Forbes India: Economic Survey says R&D is 0.6% of GDP","https://www.forbesindia.com/article/budget-2026/indias-expenditure-on-rd-just-0-6-percent-of-gdp-economic-survey/2990842/1","Press"],
  rdi:["IMPRI: RDI Scheme progress","https://www.impriindia.com/centres/center-for-human-dignity-and-development/research-development-and-innovation-rdi-scheme-strengthening-indias-innovation-ecosystem/","Analysis"],
  dst:["DST: R&D Statistics at a Glance 2022-23","https://dst.gov.in/sites/default/files/Updated%20RD%20Statistics%20at%20a%20Glance%202022-23.pdf","Official"],
  gii:["WIPO: Global Innovation Index 2025","https://www.wipo.int/web-publications/global-innovation-index-2025/en/gii-2025-results.html","Index"],
  gpi:["Institute for Economics and Peace: Global Peace Index","https://gpi.economicsandpeace.org/","Index"],
  gpi26:["Outlook Traveller: Global Peace Index 2026, top 10 and India 127th","https://www.outlooktraveller.com/News/global-peace-index-2026-the-10-most-peaceful-countries-in-the-world-right-now","Press"],
  gpi25:["IEP: Global Peace Index 2025 poster","https://www.visionofhumanity.org/wp-content/uploads/2025/06/Global-Peace-Index-2025-Map-Poster-A3.pdf","Index"],
  cpi25:["Drishti IAS: Corruption Perceptions Index 2025","https://www.drishtiias.com/current-affairs-news-analysis-editorials/news-analysis/16-02-2026/print/manual","Secondary"],
  rsf:["RSF: India country page (2026 index)","https://rsf.org/en/country/india","Index"],
  rsf2:["The Wire: India 157th on RSF 2026","https://m.thewire.in/article/media/india-is-157th-out-of-180-countries-on-rsfs-2026-world-press-freedom-index","Press"],
  fh:["Freedom House: India, Freedom in the World 2026","https://freedomhouse.org/country/india/freedom-world/2026","Index"],
  fh2:["The Wire: India in Freedom in the World 2026 (62/100)","https://m.thewire.in/article/rights/india-and-the-global-democratic-backslide-insights-from-freedom-in-the-world-2026-report","Press"],
  eac:["Tribune: PM's Economic Advisory Council paper challenges global indices","https://www.tribuneindia.com/news/nation/pms-economic-council-challenges-global-indices-asks-world-bank-to-ensure-their-accountability-453619/amp","Press"],
  sir:["All India Radio: 91 lakh names removed in West Bengal roll revision","https://www.newsonair.gov.in/assembly-election-2026-eci-revises-voter-list-removing-over-91-lakh-names-in-west-bengal","Official"],
  sir2:["Wikipedia: Special Intensive Revision (Bihar, Supreme Court ruling)","https://en.wikipedia.org/wiki/Special_Intensive_Revision","Secondary"],
  elec:["India TV: 2026 assembly election results, party-wise seats","https://www.indiatvnews.com/news/india/assembly-elections-2026-check-complete-party-wise-seats-in-west-bengal-tamil-nadu-assam-kerala-puducherry-2026-05-05-1039978","Press"],
  imfc:["Vision IAS: IMF gives India's national accounts a 'C'","https://visionias.in/current-affairs/upsc-daily-news-summary/article/2025-11-28/the-hindu/economics-indian-economy/imf-gives-india-a-c-on-its-gdp-and-other-national-accounts-data-the-second-lowest-grade","Secondary"],
  pov:["The Week/PTI: World Bank, extreme poverty 5.3% in 2022-23","https://www.theweek.in/wire-updates/business/2025/06/07/del44-biz-world-bank-ld-poverty.html","Press"],
  pov2:["Vision IAS: World Bank poverty data and comparability caveats","https://visionias.in/current-affairs/upsc-daily-news-summary/article/2025-04-26/business-standard/society/india-slashed-extreme-poverty-to-23-in-fy23-shows-world-bank-data","Secondary"],
  gini:["Business Today: World Bank Gini 25.5 vs income Gini 62","https://www.businesstoday.in/amp/latest/economy/story/world-bank-indias-extreme-poverty-drops-to-23-employment-growth-outpaces-working-age-population-473528-2025-04-24","Press"],
  air:["Drishti IAS: IQAir World Air Quality Report 2025","https://www.drishtiias.com/state-pcs-current-affairs/world-air-quality-report-2025/print_manually","Secondary"],
  whr:["Drishti IAS: World Happiness Report 2026","https://www.drishtiias.com/daily-updates/daily-news-analysis/world-happiness-report-2026/print_manually","Secondary"],
  whr2:["The Goan: World Happiness Report 2026 scores","https://www.thegoan.net/editorial/world-happiness-ranking-2026/151610.html","Press"],
  gender:["The Week/PTI: Global Gender Gap 2025, India 131 of 148","https://www.theweek.in/wire-updates/national/2025/06/12/del45-wef-gender-gap-ld-india.html","Press"],
  ghi:["Global Hunger Index 2025 summary (secondary only)","https://videohighlight.com/v/Xu3Kh0SHIvk","Secondary"],
  renounce:["Tribune: 2.16 lakh renounced citizenship in 2023","https://www.tribuneindia.com/news/diaspora/2-16-lakh-indians-renounced-their-citizenship-in-2023-government-data/","Press"],
  renounce24:["Deccan Herald: over 2 lakh renounced in 2024","https://www.deccanherald.com/india/over-2-lakh-indians-renounced-citizenship-in-2024-govt-tells-lok-sabha-3672722","Press"],
  henley:["ThePrint: Henley report on millionaire outflows","https://theprint.in/economy/fewer-millionaires-set-to-emigrate-this-yr-india-produces-far-more-than-those-leaving-henley-report/2142784/","Press"],
  henley25:["Tribune: 3,500 millionaires forecast to leave in 2025","https://www.tribuneindia.com/news/diaspora/3500-millionaires-to-leave-india-in-2025-wealth-exodus-of-26-billion","Press"],
  h1b:["GoElite: H-1B fee extended to Sept 2027, still court-blocked","https://goelite.com/blogs/trump-extends-h1b-fee-despite-court-block","Press"],
  h1bk:["Klasko: $100,000 H-1B fee blocked again (August 2026)","https://www.klaskolaw.com/august-2026-100000-h-1b-fee-blocked-again/","Analysis"],
  migr:["Business Standard: 2025 recap, migration options for Indians tightened","https://www.business-standard.com/immigration/2025-recap-immigration-settlement-rules-squeezed-options-for-indians-125121800128_1.html","Press"],
  trade:["ClearTax: US tariff on India, Feb 2026 deal","https://cleartax.in/s/us-tariff-on-india","Analysis"],
  trade2:["Reuters via Bilaterals: India-US trade deal and tariff probes (June 2026)","https://www.bilaterals.org/india-us-trade-deal-can-be?lang=en","Press"],
  hormuz:["Wright Research: Hormuz share of India's energy imports","https://www.wrightresearch.in/blog/is-india-in-an-oil-gas-crisis-iran-war-strait-of-hormuz-disruption/","Analysis"],
  lpg:["Wikipedia: India in the 2026 Iran war","https://en.wikipedia.org/wiki/India_in_the_2026_Iran_war","Secondary"],
  sec25:["Tribune: 2025 internal security review","https://www.tribuneindia.com/news/26-11mumbaiattack/from-pahalgam-to-manipur-2025-was-a-mixed-bag-for-indias-internal-security-landscape","Press"],
  sindoor:["The Diplomat: a year after Operation Sindoor","https://thediplomat.com/2026/05/a-year-after-operation-sindoor-rising-risks-and-deepening-instability/","Analysis"],
  naxal:["Morung Express/IANS: 'Naxal-free' statement in Lok Sabha","https://morungexpress.com/india-naxal-free-maoist-leadership-decimated-hm-amit-shah","Press"],
  farm:["NCAER: towards doubling farmers' income (Dalwai committee)","https://ncaer.org/?p=16193","Analysis"],
  farm2:["Outlook: farmers' income, target vs reality","https://outlookindia.com/national/centre-wanted-to-double-farmers-income-by-2022-what-is-the-reality--news-51625","Press"],
  bullet:["Deccan Herald: bullet train cost may reach Rs 1.98 lakh crore","https://www.deccanherald.com/india/mumbai-ahmedabad-bullet-train-cost-may-rise-to-rs-198-lakh-crore-due-to-delays-3850615","Press"],
  bullet2:["Infrastructure Today: bullet train delay","https://infrastructuretoday.co.in/?p=39583","Press"],
  renew:["Deccan Herald: 50% non-fossil capacity milestone","https://www.deccanherald.com/india/india-hits-50-non-fossil-power-milestone-ahead-of-2030-clean-energy-target-3629888","Press"],
  gniw:["Wikipedia: GNI (PPP) per capita by country (World Bank 2024)","https://en.wikipedia.org/wiki/List_of_countries_by_GNI_(PPP)_per_capita","Secondary"],
  gnid:["Trading Economics: Denmark GNI per capita PPP","https://tradingeconomics.com/denmark/gni-per-capita-ppp-us-dollar-wb-data.html","Secondary"],
  gnis:["Trading Economics: Sweden GNI per capita PPP","https://tradingeconomics.com/sweden/gni-per-capita-ppp-us-dollar-wb-data.html","Secondary"],
  gniw2:["World Bank data: GNI per capita, PPP","https://data.worldbank.org/indicator/NY.GNP.PCAP.PP.CD","Official"],
  wbgrowth:["Tribune: World Bank on the growth India needs to 2047","https://www.tribuneindia.com/news/business/indias-economy-grows-7-8-in-q1-2025-26","Press"],
  aser:["PARI: ASER (Rural) 2024 summary","https://ruralindiaonline.org/en/library/resource/annual-status-of-education-report-rural-2024","Secondary"],
  aser2:["IAS Parliament: ASER 2024 key highlights (enrolment and dropouts)","https://shankariasparliament.com/current-affairs/annual-status-of-education-report-aser-2024","Secondary"],
  ncrb:["IASGyan: NCRB Crime in India 2023","https://www.iasgyan.in/daily-current-affairs/ncrb-crime-in-india-2023-report-trends-challenges-and-insights","Secondary"],
  ncrb2:["ETV Bharat: murders, cybercrime and metro crime, NCRB 2023","https://www.etvbharat.com/en/!bharat/dip-in-murders-cybercrimes-crimes-against-sts-spiked-ncrb-2023-enn25093001359","Press"],
  ncrbw:["The Week/PTI: crimes against women, NCRB 2023","https://www.theweek.in/wire-updates/national/2025/09/30/del31-ncrb-women.html","Press"],
  srs:["Vikaspedia: SRS 2023 child mortality","https://en.vikaspedia.in/viewcontent/health/health-directory/india-achieves-significant-landmarks-in-reduction-of-child-mortality?lgn=en","Secondary"],
  nfhs:["Down To Earth: stunting and anaemia (NFHS-5, told to Parliament)","https://www.downtoearth.org.in/amp/story/governance/as-told-to-parliament-july-28-2023-33-8-children-under-5-years-of-age-are-stunted-57-women-are-anaemic-90907","Press"],
  owid:["Our World in Data: health in India","https://ourworldindata.org/profile/health/india","Analysis"],
  census:["Business Today: Census 2027 begins April 1, 2026","https://www.businesstoday.in/amp/india/story/initial-phase-of-census-2027-to-begin-on-april-1-houselisting-to-be-done-within-30-day-period-509920-2026-01-08","Press"],
  census2:["Onmanorama: Census 2027 phases, caste question, budget","https://www.onmanorama.com/news/india/2026/03/25/census-2027-caste-questions.amp.html","Press"],
  census3:["Anantam IAS: Census 2027, 16-year gap","https://anantamias.com/current-affairs/29-march-2026/","Secondary"],
  npa:["RBI Financial Stability Report, June 2026 (via JKB Financial)","https://www.jkbfsl.com/market/equity/news-analysis/news_details/Economy_News/1707844","Secondary"],
  npa25:["Business Standard: bank gross NPA at 15-year low (March 2025)","https://www.business-standard.com/finance/news/indian-scheduled-commercial-banks-gross-npa-ratio-at-15-year-low-125070101394_1.html","Press"],
  npa21:["Business Standard: gross NPA history (7.5% in March 2021)","https://business-standard.com/topic/gross-npas","Press"],
  remit:["IANS/RBI: remittances of $135.46 billion in FY25","https://ianslive.in/remittances-by-indians-working-abroad-scale-record-high-of-135-billion-in-fy-25--20250701124204","Press"],
  unmig:["Vision IAS: UN migration report, students and displacement","https://visionias.in/current-affairs/upsc-daily-news-summary/article/2026-05-05/business-standard/economy/india-tops-global-remittances-with-over-137-billion-inflows-in-2024-un","Secondary"],
  upi:["Free Press Journal: UPI record 24.51 billion in August 2026","https://www.freepressjournal.in/india/upi-transactions-hit-record-2451-billion-in-august-festive-demand-drives-growth","Press"],
  ggdebt:["Business Standard: IMF cautions on debt, Centre disagrees","https://www.business-standard.com/economy/news/imf-cautions-india-on-govt-debt-vulnerabilities-centre-disagrees-123121901166_1.html","Press"],
  ggdebt2:["Deccan Herald: India calls IMF debt warning a worst case","https://www.deccanherald.com/business/economy/india-says-imf-debt-warning-a-worst-case-scenario-2822787","Press"],
  debtst:["Anantam IAS: government debt and state debt stress","https://anantamias.com/?p=11972","Secondary"],
  manipur:["Catholic Connect: Manipur, displacement and reconciliation (Feb 2026)","https://catholicconnect.in/news/government-steps-up-relief-as-cm-calls-for-healing-in-conflict-hit-manipur","Secondary"],
  manipur2:["News Arena: Manipur updates, April-May 2026","https://www.newsarenaindia.com/tag/manipur-idps","Press"],
  gniatlas:["World Bank data: GNI per capita, Atlas method","https://data.worldbank.org/indicator/NY.GNP.PCAP.CD","Official"],
  draft:["The uploaded draft (2026_TAX.html). Used only where marked 'draft'.","","Draft"]
};
const KEYS = Object.keys(SRC);
const c = (...ks) => ks.map(k => {
  const i = KEYS.indexOf(k) + 1; const s = SRC[k];
  if (!s) return "";
  return s[1] ? `<a class="cite" href="${s[1]}" target="_blank" rel="noopener" title="${s[0].replace(/"/g,"'")}">[${i}]</a>` : `<span class="cite" title="${s[0]}">[d]</span>`;
}).join("");
