"use strict";
/* ---------- SOURCES ---------- */
const SRC = {
  gdpq1:["MoSPI press note: GDP estimates, Q1 2026-27","https://www.mospi.gov.in/uploads/latestReleases/latest_release_1788172583113_d65a77cf-240e-4491-82ee-59f78618fa41_Press_Note_on_GDP_Estimates_for_Q1_2026-27.pdf","Official"],
  gdpnew:["MoSPI press note: new GDP series, base year 2022-23","https://www.mospi.gov.in/uploads/latestReleases/latest_release_1772189865181_f040336d-bc57-4aed-b80f-586d9ccb279e_Press_Note_on_New_Series_of_GDP_Estimates_with_Base_Year_2022-23_27022026.pdf","Official"],
  gdpdebate:["Onmanorama: explainer on the GDP rebase and deflator debate","https://www.onmanorama.com/news/business/2026/09/05/did-modi-government-deliberately-doctor-gdp-figures-to-project-illusory-growth.html","Press"],
  imf6:["DSIJ: IMF April 2026 table puts India 6th","https://insights.dsij.in/dsijarticledetail/india-slips-to-6th-what-the-imfs-latest-gdp-rankings-actually-tell-us-id010-56633","Press"],
  budgetprs:["PRS: Union Budget 2026-27 analysis","https://prsindia.org/files/budget/budget_parliament/2026/Union_Budget_Analysis-2026-27.pdf","Analysis"],
  exprs:["PRS: Analysis of expenditure 2026-27","https://prsindia.org/files/budget/budget_parliament/2026/Analysis_of_Expenditure_2026-27.pdf","Analysis"],
  gst:["Business Standard: GST collections, August 2026","https://www.business-standard.com/economy/news/gst-collections-august-2026-gross-revenue-imports-refunds-126090100504_1.html","Press"],
  gstoct:["AIR: GST collections rise 4.6% in October 2025 despite rate cuts","https://www.newsonair.gov.in/gst-collections-rise-4-6-to-over-%E2%82%B91-95-lakh-crore-in-october-despite-rate-cuts/","Official"],
  itr:["Business Standard: 6.68% of population filed returns in FY24 (reply in Parliament)","https://www.business-standard.com/finance/news/only-6-68-of-population-filed-income-tax-return-in-fy24-govt-tells-house-124121700768_1.html","Press"],
  slabs:["Outlook Money: new-regime income tax slabs","https://www.outlookmoney.com/tax/income-tax-slabs-for-fy-2025-26-key-faqs-taxpayers-should-know-for-effective-tax-planning","Press"],
  ita25:["ClearTax: Income-tax Act 2025 FAQ (in force from 1 April 2026)","https://cleartax.in/s/income-tax-act-2025-frequently-asked-questions","Analysis"],
  oecd:["OECD: Revenue Statistics 2025","https://www.oecd.org/en/publications/2025/12/revenue-statistics-2025_07ca0a8e.html","Official"],
  taxf:["Tax Foundation: top personal income tax rates in Europe","https://taxfoundation.org/data/all/eu/top-personal-income-tax-rates-europe/","Analysis"],
  rbi:["Forbes India: RBI policy, August 2026","https://www.forbesindia.com/article/news/rbi-mpc-live-updates-august-2026-repo-rate-sanjay-malhotra-policy-announcement-liveblog/2996705/1","Press"],
  cpi:["Trading Economics: India CPI inflation","https://tradingeconomics.com/india/inflation-cpi","Secondary"],
  fx:["Trading Economics: Indian rupee","https://tradingeconomics.com/india/currency","Secondary"],
  fx2:["Daily Pioneer: rupee closes at 95.89","https://dailypioneer.com/news/slug-lite/rupee-closes-unchanged-at-95-89-against-us-dollar?year=2026","Press"],
  fcnr:["Finnovate: why the rupee is weak despite dollar inflows","https://www.finnovate.in/learn/blog/why-rupee-weak-despite-dollar-inflows-2026","Analysis"],
  resv:["Wikipedia: Foreign-exchange reserves of India (RBI weekly data)","https://en.wikipedia.org/wiki/Foreign-exchange_reserves_of_India","Secondary"],
  monsoon:["Business Today: weakest monsoon in years","https://www.businesstoday.in/india/story/india-monsoon-rainfall-deficit-17-year-low-crop-food-inflation-fears-556311-2026-09-18","Press"],
  foodinf:["News24: El Nino, monsoon deficit and food inflation","https://news24online.com/india/el-nino-2026-india-heads-for-driest-monsoon-since-2009-as-15-rainfall-deficit-raises-crop-food-inflation-fears/927931","Press"],
  plfsq:["Policy Edge: PLFS quarterly bulletin, April-June 2026","https://www.policyedge.in/p/q1-2026-plfs-shows-youth-unemployment-rising-as-labour-participation-softens","Analysis"],
  plfsa:["PIB: PLFS annual report 2025","https://www.pib.gov.in/PressReleasePage.aspx?PRID=2246009&reg=3&lang=1","Official"],
  plfsm:["Civilsdaily: PLFS monthly bulletin, June 2026","https://www.civilsdaily.com/news/periodic-labour-force-survey-plfs-monthly-bulletin-june-2026/","Secondary"],
  mfg:["India Sea Trade News: manufacturing share of GDP (DPIIT)","https://indiaseatradenews.com/?p=97454","Press"],
  nha:["PIB: National Health Accounts 2022-23","https://www.pib.gov.in/PressReleasePage.aspx?PRID=2265816&lang=1&reg=3","Official"],
  nhp:["Tribune: health spending and the 2.5% pledge","https://www.tribuneindia.com/news/nation/declining-trends-in-out-of-pocket-health-spending-419160","Press"],
  edu:["Tribune: education spending near 4% vs 6% target (Azim Premji University)","https://www.tribuneindia.com/news/india/indias-education-spending-remains-at-4-of-gdp-below-neps-6-target/","Press"],
  edu2:["Careers360: Economic Survey, education at 2.7% of GDP","https://news.careers360.com/economic-survey-india-highlights-percentage-gdp-education-budget-central-state-government/amp","Press"],
  hdr:["UN India: Human Development Report 2025, India data","https://india.un.org/en/node/294474","Official"],
  hdrtop:["UNDP India: India ranks 130 of 193","https://www.undp.org/india/press-releases/indias-human-development-continues-make-progress-ranks-130-out-193-countries","Official"],
  rd:["Electronics For You: DST R&D statistics 2025-26","https://www.electronicsforyou.biz/industry-buzz/indias-rd-spending-rises-but-research-intensity-remains-below-1-of-gdp/","Press"],
  rd2:["Forbes India: Economic Survey says R&D is 0.6% of GDP","https://www.forbesindia.com/article/budget-2026/indias-expenditure-on-rd-just-0-6-percent-of-gdp-economic-survey/2990842/1","Press"],
  rdi:["IMPRI: RDI Scheme progress","https://www.impriindia.com/centres/center-for-human-dignity-and-development/research-development-and-innovation-rdi-scheme-strengthening-indias-innovation-ecosystem/","Analysis"],
  dst:["DST: R&D Statistics at a Glance 2022-23","https://dst.gov.in/sites/default/files/Updated%20RD%20Statistics%20at%20a%20Glance%202022-23.pdf","Official"],
  gii:["WIPO: Global Innovation Index 2025","https://www.wipo.int/web-publications/global-innovation-index-2025/en/gii-2025-results.html","Index"],
  gpi:["Institute for Economics and Peace: Global Peace Index","https://gpi.economicsandpeace.org/","Index"],
  gpi26:["Outlook Traveller: Global Peace Index 2026, top 10 and India 127th","https://www.outlooktraveller.com/News/global-peace-index-2026-the-10-most-peaceful-countries-in-the-world-right-now","Press"],
  gpi25:["IEP: Global Peace Index 2025 poster","https://www.visionofhumanity.org/wp-content/uploads/2025/06/Global-Peace-Index-2025-Map-Poster-A3.pdf","Index"],
  cpi25:["Drishti IAS: Corruption Perceptions Index 2025","https://www.drishtiias.com/current-affairs-news-analysis-editorials/news-analysis/16-02-2026/print/manual","Secondary"],
  rsf:["RSF: India country page (2026 index)","https://rsf.org/en/country/india","Index"],
  rsf2:["The Wire: India 157th on RSF 2026","https://m.thewire.in/article/media/india-is-157th-out-of-180-countries-on-rsfs-2026-world-press-freedom-index","Press"],
  fh:["Freedom House: India, Freedom in the World 2026","https://freedomhouse.org/country/india/freedom-world/2026","Index"],
  fh2:["The Wire: India in Freedom in the World 2026 (62/100)","https://m.thewire.in/article/rights/india-and-the-global-democratic-backslide-insights-from-freedom-in-the-world-2026-report","Press"],
  eac:["Tribune: PM's Economic Advisory Council paper challenges global indices","https://www.tribuneindia.com/news/nation/pms-economic-council-challenges-global-indices-asks-world-bank-to-ensure-their-accountability-453619/amp","Press"],
  sir:["All India Radio: 91 lakh names removed in West Bengal roll revision","https://www.newsonair.gov.in/assembly-election-2026-eci-revises-voter-list-removing-over-91-lakh-names-in-west-bengal","Official"],
  sir2:["Wikipedia: Special Intensive Revision (Bihar, Supreme Court ruling)","https://en.wikipedia.org/wiki/Special_Intensive_Revision","Secondary"],
  elec:["India TV: 2026 assembly election results, party-wise seats","https://www.indiatvnews.com/news/india/assembly-elections-2026-check-complete-party-wise-seats-in-west-bengal-tamil-nadu-assam-kerala-puducherry-2026-05-05-1039978","Press"],
  imfc:["Vision IAS: IMF gives India's national accounts a 'C'","https://visionias.in/current-affairs/upsc-daily-news-summary/article/2025-11-28/the-hindu/economics-indian-economy/imf-gives-india-a-c-on-its-gdp-and-other-national-accounts-data-the-second-lowest-grade","Secondary"],
  pov:["The Week/PTI: World Bank, extreme poverty 5.3% in 2022-23","https://www.theweek.in/wire-updates/business/2025/06/07/del44-biz-world-bank-ld-poverty.html","Press"],
  pov2:["Vision IAS: World Bank poverty data and comparability caveats","https://visionias.in/current-affairs/upsc-daily-news-summary/article/2025-04-26/business-standard/society/india-slashed-extreme-poverty-to-23-in-fy23-shows-world-bank-data","Secondary"],
  gini:["Business Today: World Bank Gini 25.5 vs income Gini 62","https://www.businesstoday.in/amp/latest/economy/story/world-bank-indias-extreme-poverty-drops-to-23-employment-growth-outpaces-working-age-population-473528-2025-04-24","Press"],
  air:["Drishti IAS: IQAir World Air Quality Report 2025","https://www.drishtiias.com/state-pcs-current-affairs/world-air-quality-report-2025/print_manually","Secondary"],
  whr:["Drishti IAS: World Happiness Report 2026","https://www.drishtiias.com/daily-updates/daily-news-analysis/world-happiness-report-2026/print_manually","Secondary"],
  whr2:["The Goan: World Happiness Report 2026 scores","https://www.thegoan.net/editorial/world-happiness-ranking-2026/151610.html","Press"],
  gender:["The Week/PTI: Global Gender Gap 2025, India 131 of 148","https://www.theweek.in/wire-updates/national/2025/06/12/del45-wef-gender-gap-ld-india.html","Press"],
  ghi:["Global Hunger Index 2025 summary (secondary only)","https://videohighlight.com/v/Xu3Kh0SHIvk","Secondary"],
  renounce:["Tribune: 2.16 lakh renounced citizenship in 2023","https://www.tribuneindia.com/news/diaspora/2-16-lakh-indians-renounced-their-citizenship-in-2023-government-data/","Press"],
  renounce24:["Deccan Herald: over 2 lakh renounced in 2024","https://www.deccanherald.com/india/over-2-lakh-indians-renounced-citizenship-in-2024-govt-tells-lok-sabha-3672722","Press"],
  henley:["ThePrint: Henley report on millionaire outflows","https://theprint.in/economy/fewer-millionaires-set-to-emigrate-this-yr-india-produces-far-more-than-those-leaving-henley-report/2142784/","Press"],
  henley25:["Tribune: 3,500 millionaires forecast to leave in 2025","https://www.tribuneindia.com/news/diaspora/3500-millionaires-to-leave-india-in-2025-wealth-exodus-of-26-billion","Press"],
  h1b:["GoElite: H-1B fee extended to Sept 2027, still court-blocked","https://goelite.com/blogs/trump-extends-h1b-fee-despite-court-block","Press"],
  h1bk:["Klasko: $100,000 H-1B fee blocked again (August 2026)","https://www.klaskolaw.com/august-2026-100000-h-1b-fee-blocked-again/","Analysis"],
  migr:["Business Standard: 2025 recap, migration options for Indians tightened","https://www.business-standard.com/immigration/2025-recap-immigration-settlement-rules-squeezed-options-for-indians-125121800128_1.html","Press"],
  trade:["ClearTax: US tariff on India, Feb 2026 deal","https://cleartax.in/s/us-tariff-on-india","Analysis"],
  trade2:["Reuters via Bilaterals: India-US trade deal and tariff probes (June 2026)","https://www.bilaterals.org/india-us-trade-deal-can-be?lang=en","Press"],
  hormuz:["Wright Research: Hormuz share of India's energy imports","https://www.wrightresearch.in/blog/is-india-in-an-oil-gas-crisis-iran-war-strait-of-hormuz-disruption/","Analysis"],
  lpg:["Wikipedia: India in the 2026 Iran war","https://en.wikipedia.org/wiki/India_in_the_2026_Iran_war","Secondary"],
  sec25:["Tribune: 2025 internal security review","https://www.tribuneindia.com/news/26-11mumbaiattack/from-pahalgam-to-manipur-2025-was-a-mixed-bag-for-indias-internal-security-landscape","Press"],
  sindoor:["The Diplomat: a year after Operation Sindoor","https://thediplomat.com/2026/05/a-year-after-operation-sindoor-rising-risks-and-deepening-instability/","Analysis"],
  naxal:["Morung Express/IANS: 'Naxal-free' statement in Lok Sabha","https://morungexpress.com/india-naxal-free-maoist-leadership-decimated-hm-amit-shah","Press"],
  farm:["NCAER: towards doubling farmers' income (Dalwai committee)","https://ncaer.org/?p=16193","Analysis"],
  farm2:["Outlook: farmers' income, target vs reality","https://outlookindia.com/national/centre-wanted-to-double-farmers-income-by-2022-what-is-the-reality--news-51625","Press"],
  bullet:["Deccan Herald: bullet train cost may reach Rs 1.98 lakh crore","https://www.deccanherald.com/india/mumbai-ahmedabad-bullet-train-cost-may-rise-to-rs-198-lakh-crore-due-to-delays-3850615","Press"],
  bullet2:["Infrastructure Today: bullet train delay","https://infrastructuretoday.co.in/?p=39583","Press"],
  renew:["Deccan Herald: 50% non-fossil capacity milestone","https://www.deccanherald.com/india/india-hits-50-non-fossil-power-milestone-ahead-of-2030-clean-energy-target-3629888","Press"],
  gniw:["Wikipedia: GNI (PPP) per capita by country (World Bank 2024)","https://en.wikipedia.org/wiki/List_of_countries_by_GNI_(PPP)_per_capita","Secondary"],
  gnid:["Trading Economics: Denmark GNI per capita PPP","https://tradingeconomics.com/denmark/gni-per-capita-ppp-us-dollar-wb-data.html","Secondary"],
  gnis:["Trading Economics: Sweden GNI per capita PPP","https://tradingeconomics.com/sweden/gni-per-capita-ppp-us-dollar-wb-data.html","Secondary"],
  gniw2:["World Bank data: GNI per capita, PPP","https://data.worldbank.org/indicator/NY.GNP.PCAP.PP.CD","Official"],
  wbgrowth:["Tribune: World Bank on the growth India needs to 2047","https://www.tribuneindia.com/news/business/indias-economy-grows-7-8-in-q1-2025-26","Press"],
  aser:["PARI: ASER (Rural) 2024 summary","https://ruralindiaonline.org/en/library/resource/annual-status-of-education-report-rural-2024","Secondary"],
  aser2:["IAS Parliament: ASER 2024 key highlights (enrolment and dropouts)","https://shankariasparliament.com/current-affairs/annual-status-of-education-report-aser-2024","Secondary"],
  ncrb:["IASGyan: NCRB Crime in India 2023","https://www.iasgyan.in/daily-current-affairs/ncrb-crime-in-india-2023-report-trends-challenges-and-insights","Secondary"],
  ncrb2:["ETV Bharat: murders, cybercrime and metro crime, NCRB 2023","https://www.etvbharat.com/en/!bharat/dip-in-murders-cybercrimes-crimes-against-sts-spiked-ncrb-2023-enn25093001359","Press"],
  ncrbw:["The Week/PTI: crimes against women, NCRB 2023","https://www.theweek.in/wire-updates/national/2025/09/30/del31-ncrb-women.html","Press"],
  srs:["Vikaspedia: SRS 2023 child mortality","https://en.vikaspedia.in/viewcontent/health/health-directory/india-achieves-significant-landmarks-in-reduction-of-child-mortality?lgn=en","Secondary"],
  nfhs:["Down To Earth: stunting and anaemia (NFHS-5, told to Parliament)","https://www.downtoearth.org.in/amp/story/governance/as-told-to-parliament-july-28-2023-33-8-children-under-5-years-of-age-are-stunted-57-women-are-anaemic-90907","Press"],
  owid:["Our World in Data: health in India","https://ourworldindata.org/profile/health/india","Analysis"],
  census:["Business Today: Census 2027 begins April 1, 2026","https://www.businesstoday.in/amp/india/story/initial-phase-of-census-2027-to-begin-on-april-1-houselisting-to-be-done-within-30-day-period-509920-2026-01-08","Press"],
  census2:["Onmanorama: Census 2027 phases, caste question, budget","https://www.onmanorama.com/news/india/2026/03/25/census-2027-caste-questions.amp.html","Press"],
  census3:["Anantam IAS: Census 2027, 16-year gap","https://anantamias.com/current-affairs/29-march-2026/","Secondary"],
  npa:["RBI Financial Stability Report, June 2026 (via JKB Financial)","https://www.jkbfsl.com/market/equity/news-analysis/news_details/Economy_News/1707844","Secondary"],
  npa25:["Business Standard: bank gross NPA at 15-year low (March 2025)","https://www.business-standard.com/finance/news/indian-scheduled-commercial-banks-gross-npa-ratio-at-15-year-low-125070101394_1.html","Press"],
  npa21:["Business Standard: gross NPA history (7.5% in March 2021)","https://business-standard.com/topic/gross-npas","Press"],
  remit:["IANS/RBI: remittances of $135.46 billion in FY25","https://ianslive.in/remittances-by-indians-working-abroad-scale-record-high-of-135-billion-in-fy-25--20250701124204","Press"],
  unmig:["Vision IAS: UN migration report, students and displacement","https://visionias.in/current-affairs/upsc-daily-news-summary/article/2026-05-05/business-standard/economy/india-tops-global-remittances-with-over-137-billion-inflows-in-2024-un","Secondary"],
  upi:["Free Press Journal: UPI record 24.51 billion in August 2026","https://www.freepressjournal.in/india/upi-transactions-hit-record-2451-billion-in-august-festive-demand-drives-growth","Press"],
  ggdebt:["Business Standard: IMF cautions on debt, Centre disagrees","https://www.business-standard.com/economy/news/imf-cautions-india-on-govt-debt-vulnerabilities-centre-disagrees-123121901166_1.html","Press"],
  ggdebt2:["Deccan Herald: India calls IMF debt warning a worst case","https://www.deccanherald.com/business/economy/india-says-imf-debt-warning-a-worst-case-scenario-2822787","Press"],
  debtst:["Anantam IAS: government debt and state debt stress","https://anantamias.com/?p=11972","Secondary"],
  manipur:["Catholic Connect: Manipur, displacement and reconciliation (Feb 2026)","https://catholicconnect.in/news/government-steps-up-relief-as-cm-calls-for-healing-in-conflict-hit-manipur","Secondary"],
  manipur2:["News Arena: Manipur updates, April-May 2026","https://www.newsarenaindia.com/tag/manipur-idps","Press"],
  gniatlas:["World Bank data: GNI per capita, Atlas method","https://data.worldbank.org/indicator/NY.GNP.PCAP.CD","Official"],
  eb_adr:["ADR: Bonds, trusts and missing transparency (Rs 16,518 crore of bonds; 2024-25 donations)","https://adrindia.org/content/india-electoral-trusts-political-funding","Index"],
  eb_adr2:["ADR: Electoral bonds, shaken and stirred (TMC 95%, BJD 93% via bonds)","https://adrindia.org/content/electoral-bonds-shaken-and-stirred","Index"],
  eb_trib:["Tribune: BJP got 48.4% of donations via electoral bonds, 2017-18 to 2022-23","https://www.tribuneindia.com/news/india/at-48-bjp-got-lions-share-of-donations-via-electoral-bonds-591173/amp","Press"],
  eb_bs:["Business Standard: electoral bond data, BJP, Congress, TMC (SBI release)","https://www.business-standard.com/amp/elections/lok-sabha-election/electoral-bonds-data-here-s-how-much-the-bjp-congress-and-tmc-received-124032200760_1.html","Press"],
  eb_aj:["Al Jazeera: firms probed by agencies paid parties (BJP denies wrongdoing)","https://www.aljazeera.com/news/2024/4/4/indias-electoral-bonds-laundry-corrupt-firms-paid-parties-got-cleansed","Press"],
  eb_nat:["Humanities & Social Sciences Communications: corruption in the electoral bonds scheme","https://www.nature.com/articles/s41599-025-06201-z","Analysis"],
  ed_wire:["The Wire: PMLA cases at four-year high in 2025-26, Parliament told","https://m.thewire.in/article/law/cases-under-pmla-by-enforcement-directorate-rose-to-four-year-high-in-2025-26-parliament-told/amp","Press"],
  ed_a2z:["A2Z Taxcorp: Rajya Sabha reply, 4,622 ED cases and 2,127 IT prosecutions","https://a2ztaxcorp.net/ed-registers-4622-pmla-cases-in-five-years-income-tax-department-files-2127-prosecution-cases/","Secondary"],
  ed_dh:["Deccan Herald: 193 politicians faced ED cases in 10 years, 2 convictions","https://www.deccanherald.com/india/193-politicians-faced-ed-cases-between-2015-16-and-2024-25-only-2-convictions-3452451","Press"],
  ed_wire2:["The Wire: how central agencies are used during elections (in numbers)","https://m.thewire.in/article/government/in-numbers-how-bjp-deploys-central-agencies-like-the-enforcement-directorate-during-elections","Press"],
  cag_w:["The Wire: Rs 54,282 crore in outstanding utilisation certificates, CAG","https://m.thewire.in/article/government/rs-54282-32-crore-spending-by-modi-government-unaccounted-flags-cag-report","Press"],
  cag_w2:["The Wire: beyond Rs 54,282 crore, red flags in the CAG report","https://m.thewire.in/article/economy/cag-report-narendra-modi-government-pension-savings-use-of-money","Press"],
  cag_ne:["NE Now: CAG flags Rs 54,282 crore, misclassification and suspense accounts","https://nenow.in/national/cag-flags-modi-govts-rs-54282-crore-unaccounted-spendingq.html","Press"],
  adn_sec:["CNBC: Adani, nephew settle SEC case for $18 million","https://www.cnbc.com/2026/05/15/us-sec-settlement-gautam-adani-sagar-adani-fraud-case.html","Press"],
  adn_bs:["Business Standard: Adani's US legal saga, indictment to dismissal","https://www.business-standard.com/companies/news/adani-s-us-legal-saga-from-bribery-indictment-to-criminal-case-dismissal-126081101061_1.html","Press"],
  adn_jan:["CNBC: SEC seeks to serve Adani; India's Law Ministry declined twice","https://www.cnbc.com/2026/01/23/adani-group-shares-sec-investigation-fraud.html","Press"],
  adn_sebi:["Business Today: SEBI hearings on Hindenburg-linked trades","https://www.businesstoday.in/latest/corporate/story/sebi-begins-hearings-to-recover-gains-linked-to-adani-hindenburg-trades-report-553376-2026-09-04","Press"],
  nl_int:["Newslaundry: PM internship scheme, a 99% shortfall","https://www.newslaundry.com/2026/07/21/a-flagship-2024-promise-a-99-shortfall-pm-internship-scheme-spent-nearly-as-much-on-ads-as-interns","Press"],
  nl_farm:["Newslaundry: ground report on the ICAR farmer-income claim","https://www.newslaundry.com/2026/03/27/ramnath-goenka-award-for-nl-report-challenging-modi-govts-farm-success-stories","Press"],
  neet26:["Wikipedia: 2026 NEET-UG controversy","https://en.wikipedia.org/wiki/2026_NEET_controversy","Secondary"],
  jjm_air:["AIR: Jal Shakti Minister, 15.83 crore tap connections","https://www.newsonair.gov.in/union-jal-shakti-minister-cr-patil-says-over-15-83-crore-households-now-have-tap-water-under-jal-jeevan-mission","Official"],
  jjm_aud:["Madhyamam: audit flags 26% villages without water","https://madhyamamonline.com/india/audit-flags-26-villages-without-water-centre-freezes-jal-jeevan-mission-funds-1471603","Press"],
  jjm_cag:["The Wire: CAG on Jal Jeevan Mission in Rajasthan","https://m.thewire.in/article/government/over-70-of-central-funds-allocated-for-jal-jeevan-mission-not-utilised-in-rajasthan","Press"],
  fdi_ob:["Outlook Business: net FDI fell to $6.95 bn in FY26 (Rajya Sabha reply)","https://www.outlookbusiness.com/news/govt-says-net-fdi-decline-in-recent-years-due-to-increased-repatriation-by-foreign-investors","Press"],
  fdi_fed:["The Federal: foreign investors stayed off India in 2025","https://thefederal.com/category/business/india-foreign-investments-2026-fdi-fpi-rupee-tariffs-222791","Press"],
  vbg:["ThePrint: VB-G RAM G gets Rs 95,000+ crore; MGNREGA funds cut","https://theprint.in/india/governance/vb-g-ram-g-gets-rs-95000-plus-crore-allocation-under-union-budget-2026-27-mgnrega-funds-reduced/2842622/","Press"],
  pmk:["India Water Portal: Budget 2026-27 and PM-KISAN held flat","https://www.indiawaterportal.org/governance-and-policy/union-budget-202627-what-it-means-for-water-agriculture-and-rural-livelihoods-in-india","Analysis"],
  pmg:["Sarkari Yojana: PMGKAY covers about 81.35 crore people","https://sarkariyojana.com/pm-garib-kalyan-anna-yojana/","Secondary"],
  cash_dh:["Deccan Herald (PRS): 12 states spend Rs 1.68 lakh crore on women's cash schemes","https://www.deccanherald.com/amp/story/india%2F12-states-to-spend-rs-168-lakh-crore-on-womens-cash-schemes-report-3787198","Press"],
  cash_bs:["Business Standard: women's cash schemes face fiscal reality","https://www.business-standard.com/economy/news/from-splurge-to-squeeze-women-s-cash-schemes-face-fiscal-reality-126062400901_1.html","Press"],
  cash_dp:["Daily Pioneer: cash in hand, capacity in retreat","https://dailypioneer.com/news/cash-in-hand-capacity-in-retreat","Press"],
  bihar_dh:["Deccan Herald: Bihar Rs 10,000 cash transfer before the 2025 election","https://www.deccanherald.com/amp/story/elections%2Fbihar%2Fbihar-assembly-elections-2025-rs-10000-cash-transfer-to-women-may-prove-game-changer-for-nitish-kumar-3773893","Press"],
  bihar_prs:["PRS: Bihar Budget analysis 2026-27","https://prsindia.org/budgets/states/bihar-budget-analysis-2026-27","Analysis"],
  ssf:["Lukmaan IAS: State of State Finances 2025-26 (PIB summary)","https://blog.lukmaanias.com/2026/09/08/state-of-state-finances-2025-26/","Secondary"],
  upi_bs:["Business Standard: why the government is putting a price on big UPI payments","https://www.business-standard.com/finance/news/upi-fee-why-government-is-putting-a-price-on-big-merchant-payments-126091600484_1.html","Press"],
  upi_op:["OpIndia: Finance Ministry FAQ on the 0.4% UPI MDR","https://www.opindia.com/2026/09/no-tax-on-upi-consumers-finance-ministry-says-only-0-4-mdr-to-be-levied-on-payments-to-merchants-up-to-rs-2000-npci-issues-faq-sheet/","Press"],
  upi_tt:["TechTimes: UPI merchant fee talks, USTR and parliamentary committee","https://www.techtimes.com/articles/327573/20260915/upi-merchant-fee-talks-begin-india-ends-six-year-zero-charge-era-business.htm","Press"],
  upi_dt:["Digital Terminal: UPI MDR worked example with GST","https://digitalterminal.in/trending/upi-mdr-charges-return-will-customers-end-up-paying-more","Secondary"],
  upi_25:["AIR: Finance Ministry, June 2025, no plan for MDR on UPI","https://www.newsonair.gov.in/finance-ministry-says-there-is-no-plan-to-levy-mdr-charge-on-upi-transactions","Official"],
  upi_gst:["Tribune: no GST on UPI above Rs 2,000, Finance Ministry (2025)","https://www.tribuneindia.com/news/business/govt-not-considering-levying-gst-on-upi-transactions-above-rs-2000-finance-ministry","Press"],
  itact:["SCC Times: important legislations of 2025 (Income-tax Act 2025 passed without debate)","https://www.scconline.com/blog/post/2026/01/04/important-legislations-2025-yearly-roundup/","Analysis"],
  lab_k:["KPMG: final rules under the four Labour Codes (8 May 2026)","https://kpmg.com/xx/en/our-insights/gms-flash-alert/2026/flash-alert-2026-127.html","Analysis"],
  lab_f:["FactoHR: four labour codes in 2026, states still implementing","https://factohr.com/labour-law-in-india/","Secondary"],
  par_bs:["Business Standard: Monsoon Session 2026, 12 bills introduced, 11 passed","https://www.business-standard.com/india-news/parliament-monsoon-session-12-bills-introduced-11-passed-33-hrs-spent-126081300890_1.html","Press"],
  par_out:["Outlook: Parliament ends Monsoon Session with decade-low productivity","https://www.outlookindia.com/national/parliament-ends-monsoon-session-with-decade-low-productivity","Press"],
  par_prs:["PRS: functioning of Parliament, Monsoon Session 2026","https://prsindia.org/sessiontrack/monsoon-session-2026/vital-stats","Analysis"],
  par_bs2:["Business Standard: bills introduced and passed in the same session (PRS)","https://www.business-standard.com/amp/india-news/parliament-sees-rise-in-bills-introduced-and-passed-in-same-session-prs-126082200556_1.html","Press"],
  fp_ch:["Chatham House: India's foreign policy, domestic politics and economy (Jan 2026)","https://www.chathamhouse.org/2026/01/lines-between-indias-foreign-policy-domestic-politics-and-economy-will-become-increasingly","Analysis"],
  fp_eu:["Eurasia Review: EU-India FTA concluded 27 January 2026","https://www.eurasiareview.com/26022026-the-eu-india-fta-strategic-realignment-and-its-implications-for-bangladesh-oped/","Secondary"],
  fp_iran:["CNBC: Iran crisis tests India's neutral foreign policy","https://www.cnbc.com/2026/03/10/india-iran-oil-crisis-brics-diplomacy-us-china.html","Press"],
  fp_cn:["CNBC: Modi-Xi meeting at BRICS; trade record and deficit record","https://www.cnbc.com/2026/09/12/india-china-modi-xi-brics-border.html","Press"],
  fp_eaf:["East Asia Forum (Chatham House): China-India rapprochement is tactical","https://eastasiaforum.org/2026/05/25/china-india-rapprochement-is-tactical-not-strategic/","Analysis"],
  fp_pk:["Wikipedia: 2025 India-Pakistan crisis (Indus Waters Treaty suspended)","https://en.wikipedia.org/wiki/2025_India%E2%80%93Pakistan_crisis","Secondary"],
  adr_ls:["ADR: record 46% of new Lok Sabha MPs face criminal cases","https://adrindia.org/content/record-46-of-newly-elected-lok-sabha-mps-facing-criminal-cases","Index"],
  adr_wb:["The Federal (PTI): ADR on West Bengal 2026 MLAs","https://thefederal.com/elections-2026/adr-65-pc-of-new-bengal-mlas-face-criminal-cases-sharp-rise-from-2021-61-pc-crorepatis-242093","Press"],
  adr_as:["Kashmir Observer: ADR on Assam 2026 MLAs","https://kashmirobserver.net/2026/05/05/17-assam-mlas-face-criminal-cases-85-crorepatis-adr/","Press"],
  adr_st:["Indian Republic: ADR analysis of state assemblies (45% declared cases)","https://www.indianrepublic.in/2026/05/how-criminals-enter-indian-politics.html","Secondary"],
  vc_adr:["ADR: EC asks for proof under oath on 'vote chori' claims","https://www.adrindia.org/content/rahul-gandhi-vote-chori-claims-election-commission-state-ceo-seeks-proof-under-oath-rules","Index"],
  vc_tr:["Tribune: EC rubbishes Aland deletion claim","https://www.tribuneindia.com/news/india/cec-shielding-vote-chors-undermining-democracy-rahul-election-panel-rubbishes-claim","Press"],
  vc_out:["Outlook: Maharashtra SIR draft roll leaves out 2.06 crore names","https://www.outlookindia.com/national/rahul-gandhi-alleges-vote-theft-as-sir-leaves-207-crore-names-out-of-maharashtra-draft-roll","Press"],
  def_idsa:["MP-IDSA: Ministry of Defence 2026-27 budget estimates","https://idsa.in/publisher/issuebrief/ministry-of-defence-2026-27-budget-estimates-an-analysis","Analysis"],
  def_prs:["PRS: Demand for Grants 2026-27, Defence","https://prsindia.org/budgets/parliament/demand-for-grants-2026-27-analysis-defence","Analysis"],
  def_iadb:["IADB: defence budget 2026-27, bigger outlay, hard choices","https://www.iadb.in/2026/03/11/defence-budget-2026-27-bigger-outlay-hard-choices-ahead/","Analysis"],
  rail:["Impressive Times: railway accidents and Kavach (Minister's Lok Sabha reply)","https://impressivetimes.com/national/indian-railways-safety-kavach-train-accidents-2026/","Secondary"],
  rail_dd:["DD News: railway consequential accidents fall (government data)","https://ddnews.gov.in/en/indian-railways-records-best-safety-performance-in-decades-annual-accidents-fall-from-171-to-11/","Official"],
  air_w:["Wego: Air India AI171, what the record shows (Aug 2026)","https://blog.wego.com/is-air-india-safe/","Secondary"],
  air_e:["ETV Bharat: 2025 turbulent year for Indian aviation (IndiGo cancellations)","https://www.etvbharat.com/en/business/yearender-2025-a-turbulent-year-for-indian-aviation-and-what-lies-ahead-in-2026-enn25122702778","Press"],
  wbssc:["The Week: Supreme Court upholds cancelling 25,753 Bengal SSC jobs","https://www.theweek.in/news/india/2025/04/03/west-bengal-ssc-recruitment-scam-over-25-000-candidates-lose-jobs-as-sc-upholds-calcutta-hc-s-order-cancelling-whole-process.html","Press"],
  wbssc2:["Careers360 (PTI): Bengal SSC verdict details (23 lakh candidates, 24,640 posts)","https://news.careers360.com/wb-school-jobs-petitioners-move-sc-after-calcutta-hc-nullifies-over-25k-jobs","Press"],
  cm_ie:["IndiaElections.org: current chief ministers (Sept 2026)","https://indiaelections.org/chief-ministers","Secondary"],
  pci_w:["Wikipedia (MoSPI/RBI): GSDP per capita of states, 2024-25","https://en.wikipedia.org/wiki/List_of_Indian_states_and_union_territories_by_GDP_per_capita","Secondary"],
  imr_w:["Wikipedia (SRS Bulletin): infant mortality by state","https://en.wikipedia.org/wiki/List_of_Indian_states_by_infant_mortality_rate","Secondary"],
  ncrb_w:["Wikipedia (NCRB Crime in India 2023): state crime table","https://en.wikipedia.org/wiki/List_of_states_and_union_territories_of_India_by_crime_rate","Secondary"],
  ncrb_p:["NCRB: Crime in India 2023, Vol. 1","https://www.ncrb.gov.in/uploads/files/1CrimeinIndia2023PartI.pdf","Official"],
  mpi_r:["RBI Handbook of Statistics on Indian States: multidimensional poverty","https://www.rbi.org.in/scripts/PublicationsView.aspx?id=23459","Official"],
  mpi_n:["NITI Aayog: National MPI, a progress review 2023","https://www.niti.gov.in/sites/default/files/2023-08/India-National-Multidimentional-Poverty-Index-2023.pdf","Official"],
  map_s:["svg-maps/india by Victor Cazanave (CC BY 4.0), schematic map paths","https://github.com/VictorCazanave/svg-maps/tree/master/packages/india","Secondary"],
  ncrb_hr:["Tribune: NCRB 2023 crime rate and crimes against women by state","https://www.tribuneindia.com/news/haryana/state-ranks-4th-in-crime-rate-nationwide-says-ncrb-report","Press"],
  ncrb_n:["Newslaundry: Manipuri musician killing; Indian Express on untraced accused","https://www.newslaundry.com/2026/09/19/go-back-to-your-country-manipuri-musicians-killing-reignites-concerns-over-racism-against-northeasterners-and-govt-inaction","Press"],
  draft:["The uploaded draft (2026_TAX.html). Used only where marked 'draft'.","","Draft"]
};
const KEYS = Object.keys(SRC);
const c = (...ks) => ks.map(k => {
  const i = KEYS.indexOf(k) + 1; const s = SRC[k];
  if (!s) return "";
  return s[1] ? `<a class="cite" href="${s[1]}" target="_blank" rel="noopener" title="${s[0].replace(/"/g,"'")}">[${i}]</a>` : `<span class="cite" title="${s[0]}">[d]</span>`;
}).join("");
